# Generated by Django 5.2 on 2025-04-28 09:13

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('login_link', models.TextField()),
                ('amount', models.IntegerField()),
                ('devices', models.IntegerField(default=1)),
                ('expiry', models.DateTimeField(default=datetime.datetime.now)),
                ('date_subscribed', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('mac_address', models.TextField()),
                ('active', models.BooleanField(default=False)),
                ('ip', models.TextField()),
                ('user', models.TextField()),
            ],
        ),
    ]
