# Generated by Django 5.2 on 2025-04-28 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotspot_app', '0002_rename_users_hotspotusers'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenthistory',
            name='CheckoutRequestID',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='MerchantRequestID',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='MpesaReceiptNumber',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='ResultCode',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='ResultDesc',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='Status',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
