# Generated by Django 5.2 on 2025-04-28 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotspot_app', '0003_paymenthistory_checkoutrequestid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymenthistory',
            old_name='date_subscribed',
            new_name='dateSubscribed',
        ),
        migrations.RenameField(
            model_name='paymenthistory',
            old_name='login_link',
            new_name='loginLink',
        ),
        migrations.RenameField(
            model_name='paymenthistory',
            old_name='phone_number',
            new_name='phoneNumber',
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='ExternalReference',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='macAddress',
            field=models.TextField(default=''),
        ),
    ]
