# Generated by Django 5.2 on 2025-04-28 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotspot_app', '0005_alter_paymenthistory_mpesareceiptnumber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymenthistory',
            old_name='devices',
            new_name='devicesCount',
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='ipAddress',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='planType',
            field=models.TextField(default=''),
        ),
    ]
