# Generated by Django 5.2 on 2025-04-29 13:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotspot_app', '0008_remove_hotspotusers_datesubscribed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotspotusers',
            name='dateSubscribed',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='hotspotusers',
            name='expectedExpiry',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='hotspotusers',
            name='plan',
            field=models.TextField(default=''),
        ),
    ]
