# Generated by Django 5.2 on 2025-04-29 13:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotspot_app', '0009_hotspotusers_datesubscribed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotspotusers',
            name='dateSubscribed',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='hotspotusers',
            name='expectedExpiry',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='dateSubscribed',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='expiry',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
