# Generated by Django 5.2 on 2025-04-29 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotspot_app', '0010_alter_hotspotusers_datesubscribed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotspotusers',
            name='dateSubscribed',
        ),
        migrations.RemoveField(
            model_name='hotspotusers',
            name='expectedExpiry',
        ),
        migrations.RemoveField(
            model_name='hotspotusers',
            name='plan',
        ),
    ]
