# Generated by Django 5.2 on 2025-04-30 22:15

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotspot_app', '0012_hotspotusers_datesubscribed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorLogs',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('errorException', models.TextField()),
                ('traceback', models.TextField()),
                ('dateRecorded', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
